openapi: 3.2.0
info:
  title: Clari API Reference Bulk Ingest Job Status API
  version: 5.0.0
  description: '# Clari API Reference

    Clari is the heartbeat of your revenue organization and holds your most important revenue data.'
  contact:
    name: us here! We're always happy to help with any questions.
    email: support@clari.com
servers:
- url: https://api.clari.com/{basePath}
  description: Clari gateway
  variables:
    basePath:
      default: v4
      description: version identifier
security:
- api_key: []
tags:
- name: Bulk Ingest Job Status API
paths:
  /ingest/job/{jobId}:
    get:
      summary: Check the data upload status
      description: 'Upon receiving a response from the asynchronous ingest bulk upload API, make use of the provided ''jobId'' to check the status

        and result of the upload job.


        BASE URL: `https://api.clari.com/v2`


        EXAMPLE: `https://api.clari.com/v2/ingest/bulk/entity/account`'
      operationId: ingestJobStatus
      tags:
      - Bulk Ingest Job Status API
      parameters:
      - name: apikey
        in: header
        description: Authentication token
        required: true
        schema:
          type: string
      - name: partnerkey
        in: header
        description: Partner key
        required: true
        schema:
          type: string
        example: account
      - name: jobId
        in: path
        description: the job identifier of the asynchronous upload request
        required: true
        schema:
          type: string
        example: 1231244212322
      responses:
        '200':
          description: Ingestion job success response
          content:
            application/json:
              schema:
                type: object
                description: Response containing job details wrapped in a message field
                properties:
                  message:
                    type: object
                    description: Details of an async ingestion job.
                    properties:
                      jobId:
                        description: Unique identifier of the job
                        type: string
                      module:
                        description: Module name
                        type: string
                      submittedTime:
                        description: Time when the job was submitted in milliseconds
                        type: number
                      startTime:
                        description: Time when the job started in milliseconds
                        type: number
                      endTime:
                        description: Time when the job ended in milliseconds
                        type: number
                      title:
                        description: Title of the service
                        type: string
                      fileName:
                        description: Name of the file
                        type: string
                      status:
                        description: Status of the job
                        type: string
                        enum:
                        - SUCCESS
                        - IN_PROGRESS
                        - FAILED
                        - QUEUED
                        - VALIDATION_FAILED
                      message:
                        description: Message of the job
                        type: string
              example:
                message:
                  jobId: 64eef062b1a00d40e5f0bac5
                  orgId: 1234
                  userId: 12345
                  module: DATA_INGESTION
                  submittedTime: 1231244212310
                  startTime: 1231244212322
                  endTime: 1231244212340
                  title: Data Ingestion
                  fileName: file.json
                  status: SUCCESS
                  message: Ingestion successfully completed.
        '202':
          description: Data is either in progress or in queue
          content:
            application/json:
              schema:
                $ref: '#/paths/~1ingest~1job~1%7BjobId%7D/get/responses/200/content/application~1json/schema'
              example:
                message:
                  jobId: 64eef062b1a00d40e5f0bac5
                  orgId: 1234
                  userId: 12345
                  module: DATA_INGESTION
                  submittedTime: 1231244212310
                  startTime: 1231244212322
                  endTime: null
                  title: Data Ingestion
                  fileName: file.json
                  status: IN_PROGRESS
                  message: Bulk ingestion job is in progress
        '400':
          description: Ingestion job validation errors
          content:
            application/json:
              schema:
                $ref: '#/paths/~1ingest~1job~1%7BjobId%7D/get/responses/200/content/application~1json/schema'
              example:
                message:
                  jobId: 64eef062b1a00d40e5f0bac5
                  orgId: 1234
                  userId: 12345
                  module: DATA_INGESTION
                  submittedTime: 1231244212310
                  startTime: 1231244212322
                  endTime: 1231244212340
                  title: Data Ingestion
                  fileName: file.json
                  status: VALIDATION_ERROR
                  message:
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: 'Failed validation for data at path: /email 12345 is not of type ''string'''
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: 'Failed validation for data at path: /quantity Value -5 is less than or equal to the minimum of 0'''
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: 'Failed validation for data at path: / updatedAt should be greater than or equal to createdAt'''
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Payload is not an array
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: sourceEntity is missing dataSet <index>
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: records is missing for dataSet <index>
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: No entries have valid accountId for the domains
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Primary key field <field name> is missing
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Field <field name> is missing
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Duplicate record with value <field value> for primary key field <field name>
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Duplicate record with value <field value> for primary key field <field name>
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Field <field name> value <field value> is not a valid date
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Field <field name> type <field type> does not match expected type <expected name>
                  - errorCode: INVALID_INPUT_FORMAT
                    errorSummary: Field <field name> length exceeds max length of <max length>
        '401':
          description: Invalid authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid authentication credentials
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bulk ingestion job not found. Please provide correct jobId.
        '429':
          description: API rate limit has been exceeded. The api limit is 100 requests per second per api token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: API rate limit exceeded
        '500':
          description: Ingestion job internal Error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1ingest~1job~1%7BjobId%7D/get/responses/200/content/application~1json/schema'
              example:
                message:
                  jobId: 64eef062b1a00d40e5f0bac5
                  orgId: 1234
                  userId: 12345
                  module: DATA_INGESTION
                  submittedTime: 1231244212310
                  startTime: 1231244212322
                  endTime: 1231244212340
                  title: Data Ingestion
                  fileName: file.json
                  status: FAILED
                  message: Bulk ingestion job failed. Please retry ingestion.
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: header
